<a href="https://colab.research.google.com/github/spandanag333/ML_Projects/blob/main/pyconcepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
color_list=['red','green','white','purple','pink','marron']
for i in color_list:
   print(i)



red
green
white
purple
pink
marron


In [ ]:
fr_string="Goeduhub technologies"

for i in fr_string:

    print(i)



G
o
e
d
u
h
u
b
 
t
e
c
h
n
o
l
o
g
i
e
s


In [ ]:
fr_dict={1:'q',2:'w',3:'e',4:"r"}

for i in fr_dict:

    print(i)




1
2
3
4


In [ ]:
Num=[1,2,3,4,5,6,7,8,9,10]

Sum=0

for i in Num:

    Sum=Sum+i

print(Sum)

55


In [ ]:
color_list=['red','green','white','purple','pink','marron']
for i in range(len(color_list)):
  print(color_list[i])

red
green
white
purple
pink
marron


In [ ]:
s=0
for i in range(1,14,3):
    print(i)
    s=s+i
print("sum is =",s)

1
4
7
10
13
sum is = 35


In [ ]:
for i in range(5):

    print(i)

else:

    print("Finally finished!")

0
1
2
3
4
Finally finished!


In [ ]:
color_list=['red','green','white']
for i in range(2):
    for j in color_list:
           print(i,j)

0 red
0 green
0 white
1 red
1 green
1 white


In [ ]:
n=int(input("A Number ="))
i=0
while i <=n:
    i=i+1
    s=i+n
print(s)

A Number =5
11


In [ ]:
n=int(input("A Number ="))
b=5
i=0
while i <=n:
    i=i+1
    if i>b:
        break
print(i)

A Number =6
6


In [ ]:
num=int(input("Num value="))                    
while num > 0:              
    num = num -1
    if num == 3:
        continue
        print(num)
    print ('Number=', num)

Num value=5
Number= 4
Number= 2
Number= 1
Number= 0


In [ ]:
List =[1,5,6,8,77,9,6,2.,7]

for i in List:

    if i==77:

        break

    print(i)

1
5
6
8


In [ ]:
List =[1,5,6,8,77,9,6,2,7] 
for i in List: 
  if i==77: 
    continue 
print(i)

7


In [ ]:
numbers = [ 1, 2, 4, 3, 6, 5, 7,8, 9,10,11,12,13,14,15,16 ]

for number in numbers:

    if number % 2 == 0:

        pass

    else:

        print (number)

1
3
5
7
9
11
13
15


In [ ]:
string="Goeduhub Technologies" 
str = 'Goeduhub Technologies 12345'

print('str = ', str)
print('str[0] = ', str[0])
print('str[-1] = ', str[-1])
str1 = 'Python'

str2 ='String'

# concatenating strings

print('str1 + str2 = ', str1 + str2)
print('str1 * 2 =', str1 * 2)


str =  Goeduhub Technologies 12345
str[0] =  G
str[-1] =  5
str1 + str2 =  PythonString
str1 * 2 = PythonPython


In [ ]:
Str1 = "Python Programming"

# Deleting a element of string  

del Str1

# Creating new string

Str1= "Creating new string"

print(Str1)

Creating new string


In [ ]:
Str1 = "{} {} ".format('python', 'programming') 

print(Str1) 

# Positional Formatting 

Str2= "{1} {0} ".format('python','programming') 

print(Str2) 

# Keyword Formatting 

Str1 = "{g} {t} {j}".format(g = 'Goeduhub', t= 'Technologies', j = 'Jaipur') 

print(Str1) 

python programming 
programming python 
Goeduhub Technologies Jaipur


In [ ]:
a = [1, 2, 3, 4, 5]
a.append(6)

a.append(7)

a.append(7)
a


[1, 2, 3, 4, 5, 6, 7, 7]

In [ ]:
b = [8, 9]
a.append(b)


In [ ]:
a.extend(b)
a

[1, 2, 3, 4, 5, 6, 7, 7, [8, 9], 8, 9, 8, 9]

In [ ]:
a.extend(range(3))
a

[1, 2, 3, 4, 5, 6, 7, 7, [8, 9], 8, 9, 8, 9, 0, 1, 2]

In [ ]:
a.index(7)
a

[1, 2, 3, 4, 5, 6, 7, 7, [8, 9], 8, 9, 8, 9, 0, 1, 2]

In [ ]:
lst = ['a', 'b', 'c', 'd', 'e']   
lst[2:4]


['c', 'd']

In [ ]:
lst[2:]

['c', 'd', 'e']

In [ ]:
lst[:4]

['a', 'b', 'c', 'd']

In [ ]:
lst[::2]

['a', 'c', 'e']

In [ ]:
lst[::3]

['a', 'd']

In [ ]:
x,y = 3,4

print (x,y)

a,b,c = 10,11,12

print(a,b,c)

print(b)

tuple=('a','b','c','d','e','f')

print(tuple)

3 4
10 11 12
11
('a', 'b', 'c', 'd', 'e', 'f')


In [ ]:
tup = ('a','e','i','o','u') #Form a tuple with name tup

print("tup is", tup)

tup is ('a', 'e', 'i', 'o', 'u')


In [ ]:
print(tup[0])

print(tup[1])

print(tup[-1])

print(tup[-2])

print(tup[1:3])

print(tup[:3])

a
e
u
o
('e', 'i')
('a', 'e', 'i')


In [ ]:
t1=(1,2,3,4)

t2=('a','e','i','o','u') 

T=t1+t2 # add two tuples

print(T)

len(t2)

(1, 2, 3, 4, 'a', 'e', 'i', 'o', 'u')


5

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array

print(type(a))

print(a)
print(a[0], a[1], a[2])   

#Change an element of array 

a[0]=5

print(a)

<class 'numpy.ndarray'>
[1 2 3]
1 2 3
[5 2 3]


In [ ]:


b = np.array([[1,2,3],[4,5,6]])   

print(b)

print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

#Slicing in array

print(a.shape)

b = a[1:, 2:]

print(b)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 7  8]
 [11 12]]


In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a

#array "a "  is already created 

row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1)

print(row_r1.shape)  

print(row_r2)

print(row_r2.shape)

[5 6 7 8]
(4,)
[[5 6 7 8]]
(1, 4)


In [ ]:
col_r1 = a[:, 1]

col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  

print(col_r2, col_r2.shape)  

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])

print(np.array([a[0, 0], a[1, 1], a[2, 0]])) 

[1 4 5]
[1 4 5]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)

print(y)

print(x + y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [ ]:
print(x - y)

print(x * y)

print(x / y)

print(np.sqrt(x))



[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4],[8,9]])

print(np.sum(x))  

print(np.sum(x, axis=0))  

print(np.sum(x, axis=1))  
print(x.T)

27
[12 15]
[ 3  7 17]
[[1 3 8]
 [2 4 9]]


In [ ]:
import pandas as pd
import numpy as np
# simple array
data = np.array(['g','o','e','d','u','h','u','b'])
data


array(['g', 'o', 'e', 'd', 'u', 'h', 'u', 'b'], dtype='<U1')

In [ ]:
ser = pd.Series(data)
print(ser)

0    g
1    o
2    e
3    d
4    u
5    h
6    u
7    b
dtype: object


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series( np.random.random(5) , index=['a', 'b', 'c', 'd', 'e'] )
print(s1)

a    0.191484
b    0.845018
c    0.769535
d    0.496452
e    0.891557
dtype: float64


In [ ]:
data = {'pi': 3.1415, 'e': 2.71828}  # dictionary

print(data)

s3 = pd.Series ( data )

print(s3)

{'pi': 3.1415, 'e': 2.71828}
pi    3.14150
e     2.71828
dtype: float64


In [ ]:
import pandas as pd

import numpy as np

s1 = pd.Series( np.random.random(5) )

print(s1)

# Many ways to "slice" Pandas series (series have zero-based index by default):

s1[3]  # returns 4th element

s1[:2] #First 2 elements

print( s1[ [2,1,0]])

# View index values

print(s1.index)

0    0.326171
1    0.594260
2    0.007559
3    0.241663
4    0.203906
dtype: float64
2    0.007559
1    0.594260
0    0.326171
dtype: float64
RangeIndex(start=0, stop=5, step=1)


In [ ]:
print("Median:" , s1.median())

# numpy functions can be used on series as usual:

s1[s1 > s1.median()]
s1.values

Median: 0.24166280906166016


0    0.326171
1    0.594260
dtype: float64

In [ ]:
s5 = pd.Series (range(6))
print(s5)
print(s5[:-1])
print(s5[1:])
s5[1:] + s5[:-1]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
0    0
1    1
2    2
3    3
4    4
dtype: int64
1    1
2    2
3    3
4    4
5    5
dtype: int64


0    NaN
1    2.0
2    4.0
3    6.0
4    8.0
5    NaN
dtype: float64

In [ ]:
mys = pd.Series( np.random.randn(5))
print(mys)
print(mys.empty)
print(mys.head(2))
print(mys.tail(2))
print(mys.values)
print(mys.dtype)

0   -1.188129
1    0.392936
2    0.017280
3   -1.487972
4    0.821986
dtype: float64
False
0   -1.188129
1    0.392936
dtype: float64
3   -1.487972
4    0.821986
dtype: float64
[-1.18812907  0.39293635  0.01727964 -1.48797236  0.82198584]
float64
